### ISSUE TITLE
Confused about the details of Guided Adversarial Training

### ISSUE THREAD

**Issue by cxmscb** [val-iisc/GAMA-GAT#3]
Hi, I find there is something confusing in the implementation of GAT.
As shown in the Algorithm S1 of  the original paper, the single-step attack focuses on the combination of the CE loss and the regularzation loss, but in the implementation code,  the single-step attack only focuses on the CE loss, i.e., the function FGSM_Attack_step used in training.

**Comment by selous123** [comment]
I have also noticed this problems in code.

FGSM-AT has been experimentally proved not valided for stronger attack.

maybe the code is not the GAT-AT!!

Waiting for author to update codes.

**Comment by GaurangSriramanan** [comment]
Thank you for your interest in our work and for highlighting this. We accidentally uploaded the code for one of the ablations where the L2 term is part of only the training objective, and not the attack. 
Apologies for the confusion and delay, the code has been updated.
